### ISSUE TITLE
뒤로가기 및 더보기 버튼이 있고 타이틀을 넣을 수 있는 네비게이션바 개발

### ISSUE THREAD

**Issue by qorlgns1** [soon-my-room/soon_my_room#50]
하나의 컴포넌트를 이용해서 세가지를 처리

![스크린샷 2022-07-09 오전 11 17 53](https://user-images.githubusercontent.com/63835963/178087942-9fffc01b-74ad-4263-9224-280cafc08676.png)
![스크린샷 2022-07-09 오전 11 24 35](https://user-images.githubusercontent.com/63835963/178088109-71f4f204-5fcc-47f9-8fa4-262af4c66c1d.png)
![스크린샷 2022-07-09 오후 12 24 28](https://user-images.githubusercontent.com/63835963/178089745-d4f6fb2d-9d78-4d60-8cfa-43cb40c21c6f.png)

**Comment by qorlgns1** [comment]
네비게이션바 컴포넌트 사용방법
```
<TopNavBasic viewMore />
<TopNavBasic title='상단 네비게이션 타이틀' viewMore />
<TopNavBasic title='더보기 버튼 없애기' />
```

**Comment by CosmicLatte009** [comment]
야호 감사합니다 기훈님~! 당장 써야지
